version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./templates:/usr/share/nginx/html
      - ./static:/usr/share/nginx/html/static
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webcv.rule=Host(`portfolio.jack-sanders.uk`, `portfolio.local.jack-sanders.uk`)"
      - "traefik.http.middlewares.webcv-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.webcv-secure.entrypoints=https"
      - "traefik.http.routers.webcv-secure.rule=Host(`portfolio.jack-sanders.uk`, `portfolio.local.jack-sanders.uk`)"
      - "traefik.http.routers.webcv-secure.tls=true"
      - "traefik.http.routers.webcv-secure.service=webcv"
      - "traefik.http.services.webcv.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

  contact:
    build:
      context: .
      dockerfile: dockerfile_node
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.contact.rule=Host(`contact.local.jack-sanders.uk`)"
      - "traefik.http.middlewares.contact-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.contact-secure.entrypoints=https"
      - "traefik.http.routers.contact-secure.rule=Host(`contact.local.jack-sanders.uk`)"
      - "traefik.http.routers.contact-secure.tls=true"
      - "traefik.http.routers.contact-secure.service=contact"
      - "traefik.http.services.contact.loadbalancer.server.port=3333"
      - "traefik.docker.network=proxy"

networks: 
  proxy:
    external: true
