version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    #ports:
    #  - "8080:80"
    volumes:
      - ./templates:/usr/share/nginx/html
      - ./static:/usr/share/nginx/html/static
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webcv.rule=Host(`portfolio.jack-sanders.uk`, `portfolio.local.jack-sanders.uk`)"
      - "traefik.http.middlewares.webcv-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.webcv-secure.entrypoints=https"
      - "traefik.http.routers.webcv-secure.rule=Host(`portfolio.jack-sanders.uk`, `portfolio.local.jack-sanders.uk`)"
      - "traefik.http.routers.webcv-secure.tls=true"
      - "traefik.http.routers.webcv-secure.service=webcv"
      - "traefik.http.services.webcv.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"


networks: 
  proxy:
    external: true