version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./templates:/usr/share/nginx/html
      - ./static:/usr/share/nginx/html/static
