events {}
http {
    include mime.types;
    types {
        text/css css plain;
    }
    server {
        listen 80;
        root /usr/share/nginx/html;

        location / {
            try_files $uri $uri/ @htmlext;
        }

        location @htmlext {
            rewrite ^(.*)$ $1.html last;
        }

        location /static/ {
            autoindex on;
            alias /usr/share/nginx/html/static/;
        }

        location /\.css {
            default_type text/css;
        } 
    }
}